/* EuroScout ecosystem UI. Existing data, editors and authentication remain authoritative. */
const ES_ORDER='euroscout:dashboardOrder:v1';
const ES={role:'Guard',metric:'pir',rankLimit:5,noteLimit:5,statLimit:5,arrange:false,tab:'Overview',profile:null,returnPlayer:null};
function esEl(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
function esButton(text,fn,cls='es-button'){const b=esEl('button',cls,text);b.type='button';b.onclick=fn;return b;}
function esPanel(title){const n=esEl('section','panel es-panel');n.appendChild(esEl('h3',null,title));return n;}
function esReadOrder(){try{return JSON.parse(localStorage.getItem(ES_ORDER))||{};}catch(e){return {};}}
function esRanking(a,b){const d=effRating(b)-effRating(a);if(d)return d;const o=esReadOrder()[a.role]||[],x=o.indexOf(gid(a)),y=o.indexOf(gid(b));return (x<0?Infinity:x)-(y<0?Infinity:y)||0;}
async function esMove(list,p,target){if(!Store.canEdit()||!p||!target||p.role!==target.role||effRating(p)!==effRating(target)||p===target)return;
 const order=esReadOrder(),ids=order[p.role]||[];list.forEach(x=>{if(!ids.includes(gid(x)))ids.push(gid(x));});const before=list.indexOf(p)>list.indexOf(target);ids.splice(ids.indexOf(gid(p)),1);ids.splice(ids.indexOf(gid(target))+(before?0:1),0,gid(p));order[p.role]=ids;localStorage.setItem(ES_ORDER,JSON.stringify(order));Sync.stampKey(ES_ORDER);render();const focus=$$('[data-es-move]').find(b=>b.dataset.esMove===p.id&&!b.disabled);if(focus)focus.focus();const ok=await Store.pushAppKey(ES_ORDER);toast(Store.enabled?(ok?'Ranking saved':'Ranking saved on this device; cloud save unavailable'):'Ranking saved on this device');}
function esNotes(p){const r=effectiveReport(p);return ['nAth','nOff','nDef','nIntel','nProj','overall'].map(k=>r[k]||'').join('\n').trim();}
function esNoteDate(p){const r=parseReport(recOf(p).report);return r._notesUpdated||recOf(p).updated_at||'';}
function esStars(p){const n=esEl('span','es-stars');const v=Math.max(0,Math.min(5,effRating(p)||0));n.textContent='★'.repeat(Math.floor(v));n.appendChild(esEl('span','es-off','★'.repeat(5-Math.floor(v))));n.setAttribute('aria-label',v+' out of 5 stars');return n;}
function esPlayerRow(p,metric){const b=esButton('',()=>openProfile(p.id),'es-player');b.setAttribute('aria-label','Open '+p.name+' profile');const av=esEl('span','es-avatar',initials(p.name)),photo=photoOf(p);if(photo){const img=esEl('img');img.src=photo;img.alt='';img.loading='lazy';img.onerror=()=>img.remove();av.appendChild(img);}b.appendChild(av);const id=esEl('span','es-identity');id.appendChild(esEl('strong',null,p.name));id.appendChild(esEl('small',null,[p.role,p.teamName].filter(Boolean).join(' · ')));b.appendChild(id);const m=typeof metric==='function'?metric(p):esStars(p);b.appendChild(typeof m==='string'?esEl('span','es-value',m):m);b.appendChild(esEl('span','es-arrow','↗'));return b;}
function esList(panel,list,limit,metric,more){if(!list.length)panel.appendChild(esEl('p','hint','No players to show yet.'));list.slice(0,limit).forEach(p=>panel.appendChild(esPlayerRow(p,metric)));if(list.length>limit)panel.appendChild(esButton('Show more →',more));}
function renderDashboard(){const app=$('#app');app.innerHTML='';const head=esEl('div','es-heading');head.innerHTML='<div><span class="es-eyebrow">Your scouting workspace</span><h1>Pro basketball. Your perspective.</h1><p>Your evaluations first. The numbers to support them.</p></div>';head.appendChild(esButton('Browse players ↗',()=>goView('scout'),'es-button es-primary'));app.appendChild(head);const grid=esEl('div','es-dashboard');app.appendChild(grid);const all=scoutPool();
 const ranks=esPanel('Your highest-rated players'),tabs=esEl('div','es-segment');['Guard','Forward','Big'].forEach(r=>{const b=esButton(r==='Big'?'Bigs':r+'s',()=>{ES.role=r;ES.rankLimit=5;render();});b.classList.toggle('active',r===ES.role);b.setAttribute('aria-pressed',String(r===ES.role));tabs.appendChild(b);});ranks.appendChild(tabs);ranks.appendChild(esEl('p','hint','Your stars · Your order within equal ratings'));const ranked=all.filter(p=>p.role===ES.role&&effRating(p)>0).sort(esRanking);
 if(Store.canEdit())ranks.appendChild(esButton(ES.arrange?'Done arranging':'Arrange ranking',()=>{ES.arrange=!ES.arrange;render();}));let dragged=null;
 ranked.slice(0,ES.rankLimit).forEach((p,i)=>{const row=esPlayerRow(p);if(!ES.arrange||!Store.canEdit()){ranks.appendChild(row);return;}const item=esEl('div','es-rank-item'),buttons=esEl('div','es-moves');item.appendChild(row);[-1,1].forEach(d=>{const t=ranked[i+d],b=esButton(d<0?'↑':'↓',()=>esMove(ranked,p,t));b.dataset.esMove=p.id;b.setAttribute('aria-label','Move '+p.name+(d<0?' up':' down'));b.disabled=!t||effRating(t)!==effRating(p);buttons.appendChild(b);});item.appendChild(buttons);item.draggable=true;item.ondragstart=e=>{dragged=p;e.dataTransfer.setData('text/plain',p.id);};item.ondragover=e=>{if(dragged&&effRating(dragged)===effRating(p))e.preventDefault();};item.ondrop=e=>{e.preventDefault();esMove(ranked,dragged,p);dragged=null;};item.ondragend=()=>dragged=null;ranks.appendChild(item);});if(!ranked.length)ranks.appendChild(esEl('p','hint','Rate players to build your personal rankings.'));if(ranked.length>ES.rankLimit)ranks.appendChild(esButton('Show more →',()=>{ES.rankLimit+=5;render();}));grid.appendChild(ranks);
 const notes=esPanel('Recent scouting notes'),noted=all.filter(p=>esNotes(p)).sort((a,b)=>esNoteDate(b).localeCompare(esNoteDate(a)));notes.appendChild(esEl('p','hint','Most recently edited · Older imported notes may be undated'));esList(notes,noted,ES.noteLimit,p=>{const d=esNoteDate(p);return d?d.slice(0,10):'Undated';},()=>{ES.noteLimit+=5;render();});grid.appendChild(notes);
 const stats=esPanel('Statistical standouts'),scope=esEl('select','es-select');scope.setAttribute('aria-label','Standout competition');STATE.data.leagues.filter(l=>!isOtherLeague(l.meta)&&!l.meta.teamsOnly).forEach(l=>{const o=esEl('option',null,l.meta.name);o.value=l.meta.id;o.selected=l.meta.id===STATE.league.meta.id;scope.appendChild(o);});scope.onchange=()=>{STATE.league=STATE.data.leagues.find(l=>l.meta.id===scope.value);render();};stats.appendChild(scope);const metrics=esEl('div','es-segment');[['pir','PIR'],['ppg','Scoring'],['apg','Playmaking'],['ts','Efficiency']].forEach(([k,l])=>{const b=esButton(l,()=>{ES.metric=k;render();});b.classList.toggle('active',ES.metric===k);metrics.appendChild(b);});stats.appendChild(metrics);const leaders=STATE.league.players.filter(p=>p.qualified&&p[ES.metric]!=null).slice().sort((a,b)=>b[ES.metric]-a[ES.metric]);esList(stats,leaders,ES.statLimit,p=>fmt(p[ES.metric])+(ES.metric==='ts'?'%':' '+{pir:'PIR',ppg:'PTS',apg:'AST'}[ES.metric]),()=>{ES.statLimit+=5;render();});grid.appendChild(stats);
 const market=esPanel('Market overview');market.appendChild(esEl('p','hint','Existing roster, transfer and agency tools'));const links=esEl('div','es-market');[['Teams','teams'],['Transfers','transfers'],['Agencies','agencies'],['Watchlist','watchlist']].forEach(([label,view])=>links.appendChild(esButton(label+' →',()=>goView(view))));market.appendChild(links);market.appendChild(esButton('Free agents →',()=>{STATE.view='teams';renderFreeAgents();esAfterRender();}));market.appendChild(esEl('p','hint','Use DragonsHub for your club shortlist and recruitment decisions.'));grid.appendChild(market);
}
function esToggleSidebar(){const narrow=innerWidth<=1000;document.body.classList.toggle(narrow?'es-nav-open':'es-nav-collapsed');if(!narrow)localStorage.setItem('euroscout:sidebarCollapsed',String(document.body.classList.contains('es-nav-collapsed')));$('#esMenu').setAttribute('aria-expanded',String(narrow?document.body.classList.contains('es-nav-open'):!document.body.classList.contains('es-nav-collapsed')));}
function esSetup(){document.body.classList.add('es-redesign');const nav=esEl('aside','es-sidebar');nav.id='esSidebar';const brand=$('#homeLogo');nav.appendChild(brand);brand.onclick=()=>goView('dashboard');brand.querySelector('.logotext').insertAdjacentHTML('beforeend','<small>PRO BASKETBALL SCOUTING</small>');const tabs=$('#tabs');tabs.prepend(esButton('Dashboard',()=>goView('dashboard')));tabs.firstChild.dataset.view='dashboard';tabs.querySelector('[data-view=scout]').textContent='Player database';const menuItems={};tabs.querySelectorAll('button[data-view]').forEach(b=>menuItems[b.dataset.view]=b);[['dashboard'],['scout'],['watchlist'],['heading','Market intelligence'],['teams'],['agencies'],['transfers'],['exhib'],['heading','Analysis & tools'],['players'],['scouting'],['glossary']].forEach(([key,label])=>{if(key==='heading')tabs.appendChild(esEl('div','es-nav-label',label));else if(menuItems[key]){if(key==='scouting')menuItems[key].textContent='Scouting matchup';tabs.appendChild(menuItems[key]);}});nav.appendChild(tabs);const foot=esEl('div','es-nav-foot');const hub=esEl('a',null,'↗ DragonsHub');hub.href='https://dragonshub.mtscouting.com/';hub.target='_blank';hub.rel='noopener';foot.appendChild(hub);foot.appendChild(esButton('‹ Collapse sidebar',esToggleSidebar));nav.appendChild(foot);document.body.prepend(nav);const dim=esButton('Close navigation',esToggleSidebar,'es-nav-dim');dim.tabIndex=-1;document.body.prepend(dim);const header=$('header .hwrap'),menu=esButton('☰',esToggleSidebar);menu.id='esMenu';menu.setAttribute('aria-label','Toggle navigation');menu.setAttribute('aria-controls','esSidebar');menu.setAttribute('aria-expanded','true');header.prepend(menu);$('#globalSearch').placeholder='Search any player…';$('#scopeSeg').hidden=true;const settings=esButton('⚙ Settings',esSettings);settings.id='esSettings';header.insertBefore(settings,$('#authBtn'));const theme=esButton('☾',()=>toggleTheme());theme.id='esTheme';theme.setAttribute('aria-label','Switch color theme');header.insertBefore(theme,$('#authBtn'));if(localStorage.getItem('euroscout:sidebarCollapsed')==='true')document.body.classList.add('es-nav-collapsed');try{applyTheme(localStorage.getItem('euroscout:theme')||'light');}catch(e){}tabs.addEventListener('click',()=>document.body.classList.remove('es-nav-open'));document.addEventListener('keydown',e=>{if(e.key==='Escape')document.body.classList.remove('es-nav-open');});let x=null;nav.addEventListener('touchstart',e=>{x=e.touches[0].clientX;},{passive:true});nav.addEventListener('touchend',e=>{if(x!=null&&e.changedTouches[0].clientX-x<-60)document.body.classList.remove('es-nav-open');x=null;},{passive:true});}
applyTheme=function(t){document.documentElement.dataset.theme=t==='dark'?'dark':'light';localStorage.setItem('euroscout:theme',document.documentElement.dataset.theme);const b=$('#esTheme');if(b)b.textContent=t==='dark'?'☀':'☾';};toggleTheme=function(){applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');};
function esScrollbars(root){root.querySelectorAll('.estwrap,.tablewrap').forEach(w=>{if(w.dataset.esScroll)return;w.dataset.esScroll='1';const bar=esEl('div','es-scroll'),left=esButton('←',()=>w.scrollBy({left:-Math.max(180,w.clientWidth*.7),behavior:'smooth'})),right=esButton('→',()=>w.scrollBy({left:Math.max(180,w.clientWidth*.7),behavior:'smooth'})),range=esEl('input');left.setAttribute('aria-label','Scroll table left');right.setAttribute('aria-label','Scroll table right');range.type='range';range.min=0;range.step=1;range.setAttribute('aria-label','Horizontal table position');bar.append(left,range,right);w.before(bar);range.oninput=()=>w.scrollLeft=+range.value;const update=()=>{if(!bar.isConnected){observer.disconnect();return;}const max=Math.max(0,w.scrollWidth-w.clientWidth);bar.hidden=max<2;range.max=max;range.value=w.scrollLeft;left.disabled=w.scrollLeft<=1;right.disabled=w.scrollLeft>=max-1;};w.addEventListener('scroll',update,{passive:true});const observer=new ResizeObserver(update);observer.observe(w);if(w.firstElementChild)observer.observe(w.firstElementChild);requestAnimationFrame(update);});}
function esAfterRender(){$('#homeLogo').onclick=()=>goView('dashboard');const active={profile:'scout',team:'teams',compare:'players',charts:'players',fit:'players'}[STATE.view]||STATE.view;$$('#tabs [data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===active);b.setAttribute('aria-current',b.dataset.view===active?'page':'false');});esScrollbars($('#app'));$('#app .es-return')?.remove();if(ES.returnPlayer&&!DRAWER_OPEN){const bar=esEl('div','es-return');bar.appendChild(esButton('← Back to '+(player(ES.returnPlayer)?.name||'player profile'),()=>{const id=ES.returnPlayer;ES.returnPlayer=null;openProfile(id);}));bar.appendChild(esButton('Dismiss',()=>{ES.returnPlayer=null;bar.remove();}));$('#app').prepend(bar);}$$('.estr,.ptable tbody tr').forEach(row=>{row.tabIndex=0;row.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&e.target===row){e.preventDefault();row.click();}};});}
const esRenderBase=render;render=function(){if(STATE.view==='dashboard')renderDashboard();else esRenderBase();esAfterRender();};
const esScoutBase=renderScout;renderScout=function(){esScoutBase();esAfterRender();const heading=$('.scouthead .title');if(heading&&heading.textContent==='Scout board')heading.textContent='Player database';};
const esPlayersBase=renderPlayers;renderPlayers=function(){esPlayersBase();esAfterRender();const groups=esEl('div','es-segment es-stats-groups');[['','Overview'],['scoring','Scoring'],['playmaking','Playmaking'],['advanced','Advanced']].forEach(([k,label])=>{const b=esButton(label,()=>{window.ES_STATS_GROUP=k==='advanced'?'':k;STATE.filters.mode=k==='advanced'?'adv':'pg';renderPlayers();});b.classList.toggle('active',k==='advanced'?STATE.filters.mode==='adv':STATE.filters.mode==='pg'&&(window.ES_STATS_GROUP||'')===k);groups.appendChild(b);});$('#app .controls')?.before(groups);};
function esSelectTab(name){ES.tab=name;$$('#drawer .es-tab').forEach(b=>{const on=b.dataset.tab===name;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;});$$('#drawer .es-tabpanel').forEach(p=>p.hidden=p.dataset.tab!==name);esScrollbars($('#drawer'));}
function esProfileLayout(p){const panesLater=[];const root=$('#drawer .dr-scroll');if(!root)return;if(ES.profile!==gid(p)){ES.tab='Overview';ES.profile=gid(p);}const sections=Array.from(root.children).filter(n=>n.classList.contains('panel'));const hero=$('#drawer .prohero-wrap'),nav=$('#drawer .profnav');nav.querySelectorAll('.btt,.pnav-cbx,.pnav-sel').forEach(n=>n.hidden=true);const scope=nav.querySelector('.inscope');if(scope){scope.setAttribute('role','group');scope.setAttribute('aria-label','Statistical comparison group');const buttons=scope.querySelectorAll('button');if(buttons[0])buttons[0].textContent='This league';if(buttons[1])buttons[1].textContent='All leagues';scope.prepend(esEl('span','es-scope-label','Compare stats with'));}const close=Array.from(nav.querySelectorAll('button')).find(b=>(b.getAttribute('onclick')||'').includes('closeDrawer'));if(close)close.textContent='← Back to previous screen';const pill=$('#drawer .ph-pills');if(pill){pill.innerHTML='';pill.appendChild(esEl('span','es-profile-meta',[posLabel(p),ageStr(p)||null,p.height?p.height+' cm':null].filter(Boolean).join(' · ')));}$('#drawer .ph-flag')?.remove();const my=$('#drawer .ph-myrate');if(my)$('#drawer .ph-id').appendChild(my);const actions=$('#drawer .ph-actions');if(actions){const right=$('#drawer .ph-rating');if(right)right.appendChild(actions);const overflow=esEl('details','es-actions-more');overflow.appendChild(esEl('summary',null,'More actions'));Array.from(actions.children).filter((n,i)=>i>=2&&!n.textContent.includes('Eurobasket')).forEach(n=>overflow.appendChild(n));if(overflow.children.length>1)actions.appendChild(overflow);}const top=$('#drawer .ph-top');if(top)Array.from(top.children).filter(n=>!n.matches('.ph-photo,.ph-id,.ph-rating')).forEach(n=>panesLater.push(n));
 const tabs=esEl('nav','es-profile-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Player profile sections');hero.after(tabs);const panes={};['Overview','Stats','Games','Shooting','Scouting','Reports','Notes'].forEach((name,i,all)=>{const b=esButton(name,()=>esSelectTab(name),'es-tab');b.dataset.tab=name;b.id='es-tab-'+name;b.setAttribute('role','tab');b.setAttribute('aria-controls','es-panel-'+name);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const ix=e.key==='Home'?0:e.key==='End'?all.length-1:(i+(e.key==='ArrowRight'?1:-1)+all.length)%all.length;esSelectTab(all[ix]);$('#es-tab-'+all[ix]).focus();}};tabs.appendChild(b);const pane=esEl('section','es-tabpanel');pane.dataset.tab=name;pane.id='es-panel-'+name;pane.setAttribute('role','tabpanel');pane.setAttribute('aria-labelledby',b.id);root.appendChild(pane);panes[name]=pane;});
 panesLater.forEach(n=>panes.Stats.appendChild(n));const overview=esEl('div','es-overview'),main=esEl('div','es-stack'),side=esEl('div','es-stack');overview.append(main,side);panes.Overview.appendChild(overview);const snapshot=esPanel('Season snapshot');snapshot.appendChild(esEl('p','hint',leagueOf(p).meta.name+' · Per game'));const stats=esEl('div','es-snapshot');[['PTS',p.ppg],['REB',p.rpg],['AST',p.apg],['PIR',p.pir],['TS%',p.ts],['GP',p.g]].forEach(([l,v])=>{const n=esEl('div');n.appendChild(esEl('b',null,fmt(v,l==='GP'?0:1)));n.appendChild(esEl('small',null,l));stats.appendChild(n);});snapshot.appendChild(stats);const comps=$('#drawer .ph-comps');if(comps)snapshot.appendChild(comps);main.appendChild(snapshot);
 sections.forEach(n=>{const heading=n.querySelector('h3')?.textContent||'';if(n.classList.contains('ph-detail')){const bioHead=esEl('div','es-bio-heading');bioHead.appendChild(esEl('h3',null,'Player Bio'));const edit=n.querySelector('.biopanel-edit');if(edit)bioHead.appendChild(edit);n.prepend(bioHead);side.appendChild(n);n.querySelectorAll('.biocell').forEach(cell=>{const label=cell.querySelector('.bilab')?.textContent,value=cell.querySelector('.bival');if(!value)return;let fn;if(label==='Nationality'&&p.country)fn=()=>filterByAttr('country',p.country,p.country);if(label==='Team')fn=()=>openTeamFromProfile(p.league,p.teamName,p.team);if(label==='League')fn=()=>openLeaguePlayers(p.league);if(fn){const text=label==='Nationality'?p.country:value.textContent;const b=esButton(text+' ↗',fn,'es-bio-link');value.replaceChildren(b);}});}
 else if(n.id==='reportPanel')panes.Notes.appendChild(n);
 else if(n.id==='scoutPanel'||/Playing style|Similar players/.test(heading))panes.Scouting.appendChild(n);
 else if(/Game log/.test(heading))panes.Games.appendChild(n);
 else if(/Season trajectory/.test(heading))main.appendChild(n);
 else panes.Stats.appendChild(n);});
 const verdict=esPanel('Scout verdict'),rep=effectiveReport(p);verdict.appendChild(esEl('p','es-verdict',rep.nProj||rep.overall||'No projection recorded yet.'));verdict.appendChild(esButton('Open scouting notes →',()=>esSelectTab('Notes')));side.appendChild(verdict);const shooting=esPanel('Shot chart');shooting.innerHTML+='<div class="hint">'+esc(leagueOf(p).meta.name)+' · Zone shooting</div>'+shotChartSVG(p);panes.Shooting.appendChild(shooting);const reports=esPanel('Reports & links');reports.appendChild(esButton('Print / save player report as PDF',()=>exportPlayerReport(p.id)));reports.appendChild(esButton('Open written scouting report',()=>esSelectTab('Notes')));reports.appendChild(esButton('Copy player link',e=>copyPlayerLink(p.id)));panes.Reports.appendChild(reports);
 const visual=esPanel('Statistical profile');[['Scoring','ppg'],['Playmaking','apg'],['Efficiency','ts'],['Rebounding','rpg']].forEach(([label,key])=>{const pct=rankOf(scopePool(p),key,p).pct;const row=esEl('div','es-percentile');row.appendChild(esEl('span',null,label));row.appendChild(esEl('b',null,pct==null?'—':Math.round(pct)));const track=esEl('div','es-track'),fill=esEl('i');fill.style.width=(pct||0)+'%';track.appendChild(fill);row.appendChild(track);visual.appendChild(row);});visual.appendChild(esEl('p','hint','Percentiles vs '+(STATE.profileScope==='all'?'all players':'league')+' · Full detail in Stats'));const summary=root.querySelector('.statsum');if(summary){summary.classList.add('es-stat-summary');main.appendChild(summary);}main.appendChild(visual);Array.from(root.children).filter(n=>n!==nav&&n!==hero&&n!==tabs&&!n.classList.contains('es-tabpanel')).forEach(n=>panes.Stats.appendChild(n));esSelectTab(ES.tab);$('#drawer').prepend(nav);hero.after(tabs);esProjection(p);if(!Store.canEdit()){$$('#drawer .phstar,#drawer #rating button').forEach(b=>b.disabled=true);$('#drawer .biopanel-edit')?.setAttribute('hidden','');$('#drawer #saveBtn')?.setAttribute('hidden','');}
}
const esProfileBase=renderProfile;renderProfile=function(){esProfileBase();const p=player(CURRENT);if(p)esProfileLayout(p);};
const esJumpBase=drawerJump;drawerJump=function(id){const n=document.getElementById(id),pane=n?.closest('.es-tabpanel');if(pane)esSelectTab(pane.dataset.tab);esJumpBase(id);};
['filterByAttr','openTeamFromProfile','openLeaguePlayers','openAgentRoster','openAgencyRoster'].forEach(name=>{const fn=window[name];if(typeof fn==='function')window[name]=function(...args){if(DRAWER_OPEN)ES.returnPlayer=CURRENT;return fn.apply(this,args);};});
const esCloseBase=closeDrawer;closeDrawer=function(silent){esCloseBase(silent);if(STATE.view==='dashboard')render();};
Object.assign(window,{render,renderScout,renderPlayers,renderProfile,drawerJump,closeDrawer,applyTheme,toggleTheme,esSetup,esSelectTab,renderDashboard});

function esSettings(){showModal('<h3>Settings</h3><p class="hint">Account, appearance and your existing sync options.</p><div id="esSettingsActions" class="es-market"></div>');const box=$('#esSettingsActions');box.appendChild(esButton('Account',()=>{hideModal();$('#authBtn').click();}));box.appendChild(esButton('Switch light / dark theme',()=>toggleTheme()));box.appendChild(esButton('Cross-device sync',()=>Sync.openSettings()));box.appendChild(esButton('Glossary',()=>{hideModal();goView('glossary');}));}
const esHeaderAuthBase=renderHeaderAuth;renderHeaderAuth=function(){esHeaderAuthBase();const b=$('#authBtn');if(Store.enabled&&Store.user&&Store.member){const label=esEl('span','es-account-label',Store.user.email);b.appendChild(label);b.setAttribute('aria-label','Account: '+Store.user.email);}};
/* Navigation changes close the profile while its own tabs leave editors mounted. */
const esGoViewBase=goView;goView=function(view){if(DRAWER_OPEN)closeDrawer();ES.returnPlayer=null;esGoViewBase(view);};
document.addEventListener('click',e=>{if(e.target.closest('#tabs [data-view]')){if(DRAWER_OPEN)closeDrawer();ES.returnPlayer=null;}},true);

// Keep the scout's projection separate from statistical analysis.
function esProjection(p){
 $$('#drawer .barometer').forEach(n=>n.remove());
 const band=levelBand(p),label=band?.label||'Not available';
 const ladder=esEl('div','es-level-ladder');ladder.setAttribute('aria-label','Projected level: '+label);ladder.appendChild(esEl('span','es-ladder-title','Projected level'));
 LEVEL_BANDS.map((name,i)=>({name,i})).reverse().forEach(({name,i})=>{const row=esButton(name,()=>{esSelectTab('Scouting');$('#esProjection')?.scrollIntoView({block:'start'});},'es-ladder-row'+(band?.i===i?' selected':''));if(band?.i===i)row.setAttribute('aria-current','true');ladder.appendChild(row);});
 ladder.appendChild(esEl('small',null,band?.manual?'Your assessment':'Automatic estimate'));$('#drawer .ph-rating')?.before(ladder);
 const panel=esPanel('Projected level');panel.id='esProjection';
 panel.appendChild(esEl('p','hint','Your assessment applies across every competition. Choose a level, or use the automatic estimate.'));
 const labelEl=esEl('label','es-level-label','Your projection');labelEl.htmlFor='esLevel';
 const select=esEl('select','es-select');select.id='esLevel';select.appendChild(new Option('Automatic (production + your rating)',''));
 LEVEL_BANDS.map((name,i)=>({name,i})).reverse().forEach(({name,i})=>select.appendChild(new Option(name,String(i))));select.value=p.projLevel==null?'':String(p.projLevel);select.disabled=!Store.canEdit();
 select.onchange=async()=>{if(!Store.canEdit())return;await window.wfFlushReport?.();ovrSaveLocal({bio:{[gid(p)||p.id]:{projLevel:select.value}}});renderProfile();toast('Projected level saved');};
 panel.append(labelEl,select,esEl('p','hint',(band?.manual?'Manual assessment: ':'Automatic estimate: ')+label));$('#es-panel-Scouting')?.prepend(panel);
}
const esEditOriginal=openEditModal;openEditModal=function(id){esEditOriginal(id);const box=$('#modal .modalbox');if(!box||!$('#editSave'))return;box.classList.add('es-edit-modal');box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label','Edit player');
 const heading=box.querySelector('h3'),close=box.querySelector('.close'),head=esEl('div','es-edit-head');heading.textContent='Edit player';head.append(heading);if(close){close.setAttribute('aria-label','Close editor');head.append(close);}box.prepend(head);
 const sub=esEl('p','es-edit-sub',player(id)?.name||'');head.append(sub);
 const grid=box.querySelector('.editgrid');const groups=[['Identity',['eName','eHeight','eWeight','eCountry','ePos','eBorn','eHand','eExt']],['Representation',['eAgent','eAgentNew','eAgency','eAgencyNew']],['Scouting assessment',['eProj']]];
 groups.forEach(([title,ids])=>{const section=esEl('section','es-edit-section');section.appendChild(esEl('h4',null,title));const fields=esEl('div','es-edit-fields');ids.forEach(id=>{const field=document.getElementById(id)?.closest('.efld');if(field)fields.appendChild(field);});section.appendChild(fields);grid.appendChild(section);});
 const footer=$('#editSave').parentElement;footer.classList.add('es-edit-footer');const extra=esEl('details','es-edit-tools');extra.appendChild(esEl('summary',null,'Backup tools'));Array.from(footer.children).filter(n=>n.id!=='editSave').forEach(n=>extra.appendChild(n));footer.before(extra);footer.prepend(esButton('Cancel',hideModal));
 box.querySelectorAll('.efld').forEach(f=>{const l=f.querySelector('label'),input=f.querySelector('input,select');if(l&&input)l.htmlFor=input.id;});
};window.openEditModal=openEditModal;
